spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: account-management
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: b2b

  mongodb:
    embedded:
      version: 4.4.17

server:
  port: 8080

transaction:
  rabbit:
    queue-name: transaction-queue
    exchange-name: transaction-exchange
    routing-key: transaction-routing
    dead-letter-routing-key: dead-letter-routing
    dead-letter-exchange: transaction-dead-letter-exchange
    dead-letter-queue-name: transaction-dead-letter-queue
payment:
  rabbit:
    queue-name: payment-queue
    exchange-name: payment-exchange
    routing-key: payment-routing
    dead-letter-routing-key: payment-dead-letter-routing
    dead-letter-exchange: payment-dead-letter-exchange
    dead-letter-queue-name: payment-dead-letter-queue

